import type { TFunction } from 'i18next'

import type { ValidateProviderResult, ValidationCategory } from '../../../../shared/settings'

// Maps a validation category to its English message. Centralized so the wizard and the settings
// page phrase failures identically.
const CATEGORY_KEYS = {
  ok: 'Connection succeeded.',
  network: 'Could not reach the endpoint. Check your network and base URL.',
  auth: 'Authentication failed. Check the API key.',
  'model-not-found': 'The model was rejected. Check the model name for this gateway.',
  'bad-url': 'The base URL is invalid. Enter a full URL like https://gateway.example/v1.',
  timeout: 'The request timed out and was stopped.',
  incompatible: "This provider isn't compatible with the active agent framework.",
  'server-error': 'The gateway or upstream service is temporarily unavailable. Try again later.',
  unknown: 'Validation failed for an unknown reason.'
} as const satisfies Record<ValidationCategory, string>

// Categories whose generic text benefits from the specific error/probe message (a timeout or network
// failure). Auth/model/bad-url already carry actionable text.
const MESSAGE_CATEGORIES = new Set<ValidationCategory>([
  'network',
  'timeout',
  'server-error',
  'unknown'
])

// Main returns provider operation failures as display-ready strings. Translate only the bounded set
// generated by Open Science itself; all other text can be gateway-supplied and must remain verbatim.
const localizeProviderResourceMessage = (message: string, t: TFunction): string => {
  if (
    message.includes(
      'Provider connection status changed. Your changes have not been saved. Test the connection again.'
    )
  )
    return t(
      'Provider connection status changed. Your changes have not been saved. Test the connection again.'
    )
  if (message.includes('Provider configuration changed. Your draft has not been saved.'))
    return t('Provider configuration changed. Your draft has not been saved.')
  switch (message) {
    case 'The provider changed while loading models. Try again.':
      return t('The provider changed while loading models. Try again.')
    case 'Remote model URLs must use HTTPS. HTTP is only allowed for localhost or loopback addresses.':
      return t(
        'Remote model URLs must use HTTPS. HTTP is only allowed for localhost or loopback addresses.'
      )
    case 'Base URL must be a valid HTTP or HTTPS URL.':
      return t('Base URL must be a valid HTTP or HTTPS URL.')
    case 'Base URL must not include query parameters or fragments.':
      return t('Base URL must not include query parameters or fragments.')
    case 'Remove credentials from the Base URL and use the API key field.':
      return t('Remove credentials from the Base URL and use the API key field.')
    case 'Provider name must not exceed 128 characters.':
      return t('Provider name must not exceed {{limit}} characters.', { limit: 128 })
    case 'Base URL must not exceed 2048 characters.':
      return t('Base URL must not exceed {{limit}} characters.', { limit: 2048 })
    case 'Model ID must not exceed 512 characters.':
      return t('Model ID must not exceed {{limit}} characters.', { limit: 512 })
    case 'API key must not exceed 16384 bytes.':
      return t('API key must not exceed {{limit}} bytes.', { limit: 16_384 })
    case 'Provider limit of 64 reached.':
      return t('Provider limit of {{limit}} reached.', { limit: 64 })
    case 'Model list response exceeded 2097152 bytes.':
      return t('Model list response exceeded {{limit}} bytes.', { limit: 2_097_152 })
    case 'Provider validation response exceeded 1048576 bytes.':
      return t('Provider validation response exceeded {{limit}} bytes.', { limit: 1_048_576 })
    case 'The vendor returned more than 2000 models.':
      return t('The vendor returned more than {{limit}} models.', { limit: 2_000 })
    case 'The vendor returned a model ID longer than 512 characters.':
      return t('The vendor returned a model ID longer than {{limit}} characters.', { limit: 512 })
    case 'Claude sign-in token must not exceed 16384 bytes.':
      return t('Claude token must not exceed {{limit}} bytes.', { limit: 16_384 })
    case 'Open Science could not find a file-backed Codex credential to import. Your existing Codex sign-in may be stored in the system credential store, which Open Science cannot import from. Continue with the Open Science Codex sign-in instead.':
      return t(
        'Open Science could not find a file-backed Codex credential to import. Your existing Codex sign-in may be stored in the system credential store, which Open Science cannot import from. Continue with the Open Science Codex sign-in instead.'
      )
    default:
      return message
  }
}

// Produces the message to show for a validation result, appending a specific server/probe message when
// the category is generic and an HTTP status when one is available.
//
// Takes `t` rather than reaching for the i18next singleton so it stays a pure function of (result,
// locale) and a test can pin the language. Known application-generated resource errors are localized;
// every other `message` passes through verbatim because it can come from the gateway.
const describeValidation = (result: ValidateProviderResult, t: TFunction): string => {
  const detail = result.message ? localizeProviderResourceMessage(result.message, t) : undefined
  // A verified endpoint the active framework cannot drive: pair the health outcome with the
  // route-mismatch message carried on the result. A failed probe keeps its own actionable category
  // copy below; fixing the endpoint first surfaces the mismatch once the probe succeeds.
  if (result.ok && result.frameworkIncompatible) {
    const base = t(
      'Connection succeeded, but this provider is not usable by the active agent framework.'
    )
    return detail ? `${base} ${detail}` : base
  }

  const base = t(CATEGORY_KEYS[result.category])

  // Some gateways return their own actionable auth text; prefer it over the generic HTTP 401/403 copy.
  if (result.category === 'auth' && detail) {
    return detail
  }

  // An incompatible pairing carries the specific route mismatch (which API format the framework needs
  // vs. what this provider speaks); surface it instead of the generic fallback.
  if (result.category === 'incompatible' && detail) {
    return detail
  }

  // A gateway that rejected the probe with its own error text (e.g. "Insufficient Balance" on a
  // billing 402) has already told us the reason — surface it instead of the generic "unknown" copy.
  if (result.category === 'unknown' && detail) {
    return result.status
      ? t('{{base}} (HTTP {{status}})', { base: detail, status: result.status })
      : detail
  }

  if (detail && MESSAGE_CATEGORIES.has(result.category)) {
    return t('{{base}} ({{detail}})', { base, detail })
  }

  if (result.status) {
    return t('{{base}} (HTTP {{status}})', { base, status: result.status })
  }

  return base
}

export { CATEGORY_KEYS, describeValidation, localizeProviderResourceMessage }
