import { expect } from '@playwright/test'
import { test } from './fixtures/electron-app'

test.use({ windowMode: 'hidden' })

test('preserves A/B drafts while resetting message editing and keeping session hover scoped', async ({ app }, testInfo) => {
  test.setTimeout(180_000)
  await app.completeOnboarding()
  const page = await app.configureFakeAgent()
  await app.showMainWindowInactive()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.getByRole('button', { name: 'New project' }).click()
  const dialog = page.getByRole('dialog', { name: 'New project' })
  await dialog.getByLabel('Name').fill('PR 2992 contract')
  await dialog.getByRole('button', { name: 'Create project' }).click()
  const composer = page.getByRole('textbox', { name: 'Ask anything' })
  const prompts = ['Alpha session question', 'Beta session question']
  const reply = page.getByText('Deterministic reply: Summarize the deterministic fixture.', {
    exact: true
  })
  for (const [index, prompt] of prompts.entries()) {
    const priorReplies = await reply.count()
    await composer.fill(prompt)
    await page.getByRole('button', { name: 'Send message' }).click()
    await expect(reply).toHaveCount(priorReplies + 1)
    await expect.poll(() => page.evaluate(() => window.api.storage.detectActive())).toEqual([])
    if (index === 0) await page.getByRole('button', { name: 'New', exact: true }).click()
  }
  const row = (title: string) => page.locator('[data-slot="session-open-button"]').filter({ hasText: title })
  const alpha = row(prompts[0])
  const beta = row(prompts[1])
  await alpha.click()
  await composer.fill('Alpha private draft')
  await beta.click()
  await expect(composer).toHaveText('')
  await composer.fill('Beta private draft')
  await alpha.click()
  await expect(composer).toHaveText('Alpha private draft')
  await beta.click()
  await expect(composer).toHaveText('Beta private draft')

  await alpha.hover()
  const preview = page.locator('[data-slot="session-preview-content"]')
  await expect(preview).toBeVisible()
  await expect(preview).toHaveAttribute('aria-label', prompts[0])
  await beta.hover()
  await expect(preview).toHaveAttribute('aria-label', prompts[1])
  await expect(preview).toHaveAttribute('data-skip-entry-animation', 'true')
  await alpha.hover()
  await expect(preview).toHaveAttribute('aria-label', prompts[0])
  await preview.getByRole('button', { name: 'Rename session title' }).click()
  await preview.getByRole('textbox', { name: 'Session title' }).fill('Unsaved alpha rename')
  await beta.hover()
  await expect(preview).toHaveAttribute('aria-label', prompts[0])
  await expect(preview.getByRole('textbox', { name: 'Session title' })).toHaveValue('Unsaved alpha rename')
  await preview.getByRole('textbox', { name: 'Session title' }).press('Escape')
  // Focus remains inside the title card after Escape, so the preview is intentionally
  // protected until a navigation action moves focus away.
  await beta.click()
  await page.mouse.move(1200, 100)
  await beta.hover()
  await expect(preview).toHaveAttribute('aria-label', prompts[1])

  await alpha.click()
  const conversation = page.getByRole('region', { name: 'Conversation' })
  await conversation.getByText(prompts[0], { exact: true }).hover()
  await conversation.getByRole('button', { name: 'Edit message' }).click()
  await conversation.getByRole('textbox', { name: 'Edit message' }).fill('Unsaved message edit')
  await beta.click()
  await expect(conversation.getByRole('textbox', { name: 'Edit message' })).toHaveCount(0)
  await alpha.click()
  await expect(conversation.getByRole('textbox', { name: 'Edit message' })).toHaveCount(0)
  await expect(conversation.getByText(prompts[0], { exact: true })).toBeVisible()
  await expect(composer).toHaveText('Alpha private draft')
  await page.screenshot({ path: testInfo.outputPath('alpha-restored.png') })
})

test('keeps keyboard and mobile session menus usable without stealing desktop focus', async ({ app }, testInfo) => {
  test.setTimeout(120_000)
  await app.completeOnboarding()
  const page = await app.configureFakeAgent()
  await app.showMainWindowInactive()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.getByRole('button', { name: 'New project' }).click()
  const dialog = page.getByRole('dialog', { name: 'New project' })
  await dialog.getByLabel('Name').fill('PR 2992 menu')
  await dialog.getByRole('button', { name: 'Create project' }).click()
  const prompt = 'Menu contract question'
  await page.getByRole('textbox', { name: 'Ask anything' }).fill(prompt)
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(
    page.getByText('Deterministic reply: Summarize the deterministic fixture.', { exact: true })
  ).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.api.storage.detectActive())).toEqual([])
  const action = page.getByRole('button', { name: `Open actions for ${prompt}` })
  await page.mouse.move(1200, 100)
  await action.focus()
  await action.press('Enter')
  await expect(page.getByRole('menu', { name: `Open actions for ${prompt}` })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(action).toBeFocused()
  // Keyboard focus may legitimately expose the session preview after the menu returns focus.

  await page.setViewportSize({ width: 375, height: 900 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await action.click()
  const menu = page.getByRole('menu', { name: `Open actions for ${prompt}` })
  await expect(menu).toBeVisible()
  const bounds = await menu.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(375)
  await menu.getByRole('menuitem', { name: 'Export', exact: true }).hover()
  const submenu = page.getByRole('menuitem', { name: 'Export conversation…' })
  await expect(submenu).toBeVisible()
  const subBounds = await submenu.boundingBox()
  expect(subBounds).not.toBeNull()
  await testInfo.attach('mobile-menu-geometry', {
    body: JSON.stringify({ bounds, subBounds, viewportWidth: 375 }),
    contentType: 'application/json'
  })
  await submenu.click()
  await expect(page.getByRole('dialog', { name: 'Export conversation' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('mobile-menu-bounds.png') })
})
