import type { UploadedAttachment } from './uploads'
import type { FileReference } from './artifacts'
import {
  MAX_ACP_MESSAGE_IMAGES_PER_MESSAGE,
  MAX_ACP_MESSAGE_IMAGE_BYTES_PER_MESSAGE,
  MAX_ACP_SESSION_IMAGE_BYTES,
  sanitizeAcpMessageImage,
  type AcpMessageImage
} from './acp'
import {
  DEFAULT_PERMISSION_PROFILE,
  normalizePermissionProfile,
  type PermissionProfileId
} from './permission-profiles'
import type { AgentFrameworkId } from './settings'
import { sanitizeActivityGroupTitle } from './activity-groups'

// One JSON file per session (sessions/<projectId>/<sessionId>.json) carries this envelope version.
export const SESSION_FILE_VERSION = 1
// Small manifest (sessions/manifest.json) that restores the user's last-open project + session.
export const SESSION_MANIFEST_VERSION = 1

export type PersistedSessionStatus = 'idle' | 'running' | 'waiting-permission' | 'error'
export type PersistedMessageRole = 'user' | 'agent'
export type PersistedMessageStatus = 'complete' | 'streaming' | 'error'
// Managed files are generated by the app artifact pipeline; the other kinds are reserved references.
export type PersistedArtifactKind = 'workspace-file' | 'external-file' | 'managed-file'

// Stores artifact references only; file bytes stay on disk under the managed artifact root.
export type PersistedArtifact = {
  id: string
  kind: PersistedArtifactKind
  path: string
  fileUrl?: string
  name?: string
  mimeType?: string
  size?: number
  mtimeMs?: number
  sha256?: string
}

// Stores uploaded file references on the user message that submitted them.
export type PersistedUploadedAttachment = UploadedAttachment

export type PersistedMessageImage = AcpMessageImage & {
  id: string
}

// Ordered structural segments of a user message, letting the bubble re-render skill/artifact
// mentions as styled pills instead of plain text. Structurally mirrors the renderer ComposerNode
// (shared cannot import renderer code). Absent on older messages, which fall back to plain content.
export type MessagePart =
  | { type: 'text'; text: string }
  | { type: 'skill'; id: string; name: string }
  | ({ type: 'artifact' } & FileReference)

export type PersistedChatMessage = {
  id: string
  role: PersistedMessageRole
  content: string
  status: PersistedMessageStatus
  streamId?: string
  responseToMessageId?: string
  eventIds: string[]
  // Links a message to session-level artifact metadata without duplicating file records per message.
  artifactIds?: string[]
  uploads?: PersistedUploadedAttachment[]
  // Bounded raster blocks emitted directly by ACP agent_message_chunk notifications.
  images?: PersistedMessageImage[]
  // Structured mention segments for the styled user bubble; optional for backward compatibility.
  parts?: MessagePart[]
  createdAt: number
  updatedAt: number
}

export type PersistedActiveRun = {
  promptMessageId: string
  startedAt: number
}

export type PersistedToolActivityStatus = 'pending' | 'in_progress' | 'completed' | 'failed'

// A file location a tool touched; kept small so it can always be persisted.
export type PersistedToolCallLocation = {
  path: string
  line?: number | null
}

// Durable projection of a runtime tool call. Large payloads are bounded (see caps below) so
// restoring the transcript never bloats sessions.json; the UI already truncates the same fields.
export type PersistedToolActivity = {
  id: string
  kind: 'tool'
  title: string
  activityGroupId?: string
  status: PersistedToolActivityStatus
  sortIndex: number
  eventIds: string[]
  providerToolName?: string
  toolKind?: string
  // Structurally a subset of ACP ToolCallContent[]; typed loosely to keep shared free of the SDK.
  toolContent?: unknown[]
  toolLocations?: PersistedToolCallLocation[]
  rawInput?: unknown
  rawOutput?: unknown
  terminalOutput?: string
  terminalExitCode?: number | null
  createdAt: number
  updatedAt: number
}

export type PersistedActivityGroup = {
  id: string
  title: string
  sortIndex: number
  activityIds: string[]
  createdAt: number
  updatedAt: number
  completedAt?: number
}

export type PersistedChatSession = {
  id: string
  // Owning project. On load this is authoritative from the file's directory (sessions/<projectId>/).
  projectId: string
  title: string
  cwd: string
  status: PersistedSessionStatus
  agentFrameworkId?: AgentFrameworkId
  // Identifies the provider/profile session store within a framework so a restored session is never
  // resumed against an incompatible backend (for example Codex shared profile vs isolated login).
  agentBackendId?: string
  // Model selected when the latest run started. Kept with the session so a later settings change
  // cannot misattribute a failed run's diagnostic report.
  agentModel?: string
  // Per-conversation approval posture. Older session files omit it and safely restore to Ask.
  permissionProfile?: PermissionProfileId
  // Per-conversation auto-review toggle. Absent (older files) or non-true is treated as disabled;
  // only an explicit true enables it.
  autoReviewEnabled?: boolean
  // Per-session enabled compute hosts (providerIds like "ssh:alias"). Stored as an array for JSON
  // compatibility; semantically a set (single-select for now, multi-select-ready internally).
  // Absent on older sessions — treated as empty (no host enabled).
  enabledComputeHosts?: string[]
  // Pins the conversation to a dedicated section at the top of the sidebar. Absent (older files) or
  // non-true restores as unpinned; only an explicit true keeps it pinned across restarts.
  pinned?: boolean
  // Immutable Specialist UUID bound to this session (see StoredSpecialist.id). Absent (older files),
  // empty, or non-string resolves to None at runtime; a present id is re-resolved against the latest
  // settings on every execution so a stale binding can never silently expand capability.
  specialistId?: string
  messages: PersistedChatMessage[]
  activities?: PersistedToolActivity[]
  activityGroups?: PersistedActivityGroup[]
  activeRun?: PersistedActiveRun
  error?: string
  // Whether a failed run's error is worth a GitHub issue. False for a recognized failure (a provider/
  // model error the agent relayed, or one of the app's own actionable reminders); true/absent for an
  // unknown ACP-layer failure. Resolved once when the run fails and persisted so the "Report error"
  // gate survives a reload. Absent on older files — treated as reportable (the prior behavior).
  errorReportable?: boolean
  artifacts?: PersistedArtifact[]
  // Incremented only when finalized file metadata changes; text streaming leaves it untouched.
  filesRevision?: number
  createdAt: number
  updatedAt: number
}

// Restored interrupted sessions carry this error verbatim; the renderer keys its resume banner off it.
export const INTERRUPTED_SESSION_ERROR = 'Session was interrupted before the app closed.'

const MESSAGE_ROLES = new Set<PersistedMessageRole>(['user', 'agent'])
const AGENT_FRAMEWORK_IDS = new Set<AgentFrameworkId>(['claude-code', 'opencode', 'codex'])
const MESSAGE_STATUSES = new Set<PersistedMessageStatus>(['complete', 'streaming', 'error'])
const TOOL_ACTIVITY_STATUSES = new Set<PersistedToolActivityStatus>([
  'pending',
  'in_progress',
  'completed',
  'failed'
])
const SESSION_STATUSES = new Set<PersistedSessionStatus>([
  'idle',
  'running',
  'waiting-permission',
  'error'
])
const ARTIFACT_KINDS = new Set<PersistedArtifactKind>([
  'workspace-file',
  'external-file',
  'managed-file'
])

// Checks for plain JSON objects so persisted payloads can be sanitized safely.
const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

// Reads string fields from untrusted persisted payloads.
const asString = (value: unknown): string | undefined =>
  typeof value === 'string' ? value : undefined

// Reads finite numeric fields from untrusted persisted payloads.
const asNumber = (value: unknown): number | undefined =>
  typeof value === 'number' && Number.isFinite(value) ? value : undefined

// Filters mixed arrays down to strings so event and artifact ids stay JSON-safe.
const asStringArray = (value: unknown): string[] =>
  Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []

// Accepts only known message roles from persisted data.
const asMessageRole = (value: unknown): PersistedMessageRole | undefined => {
  const role = asString(value) as PersistedMessageRole | undefined

  return role && MESSAGE_ROLES.has(role) ? role : undefined
}

// Defaults unknown message statuses to complete so old or partial data stays displayable.
const asMessageStatus = (value: unknown): PersistedMessageStatus => {
  const status = asString(value) as PersistedMessageStatus | undefined

  return status && MESSAGE_STATUSES.has(status) ? status : 'complete'
}

// Defaults unknown session statuses to idle instead of restoring phantom runtime state.
const asSessionStatus = (value: unknown): PersistedSessionStatus => {
  const status = asString(value) as PersistedSessionStatus | undefined

  return status && SESSION_STATUSES.has(status) ? status : 'idle'
}

// Accepts only artifact references, never arbitrary file payload shapes.
const asArtifactKind = (value: unknown): PersistedArtifactKind | undefined => {
  const kind = asString(value) as PersistedArtifactKind | undefined

  return kind && ARTIFACT_KINDS.has(kind) ? kind : undefined
}

// Identifies UI states that cannot survive an app process shutdown.
const isSessionInterrupted = (status: PersistedSessionStatus): boolean =>
  status === 'running' || status === 'waiting-permission'

// Converts partial streamed assistant messages into visible errors after restart.
const normalizeMessageAfterRestore = (message: PersistedChatMessage): PersistedChatMessage =>
  message.status === 'streaming'
    ? {
        ...message,
        status: 'error'
      }
    : message

// Restores interrupted sessions as retryable errors because runtime state is gone.
const normalizeSessionAfterRestore = (session: PersistedChatSession): PersistedChatSession => {
  if (!isSessionInterrupted(session.status)) {
    return session
  }

  // Runtime state cannot survive process shutdown, so restore interrupted turns as retryable errors.
  return {
    ...session,
    status: 'error',
    activeRun: undefined,
    error: session.error ?? INTERRUPTED_SESSION_ERROR,
    messages: session.messages.map(normalizeMessageAfterRestore)
  }
}

// Rebuilds artifact metadata from allowed reference fields and drops embedded content.
const sanitizeArtifact = (artifact: unknown): PersistedArtifact | undefined => {
  if (!isRecord(artifact)) return undefined

  const id = asString(artifact.id)
  const kind = asArtifactKind(artifact.kind)
  const path = asString(artifact.path)

  if (!id || !kind || !path) return undefined

  const sanitized: PersistedArtifact = {
    id,
    kind,
    path
  }
  const name = asString(artifact.name)
  const fileUrl = asString(artifact.fileUrl)
  const mimeType = asString(artifact.mimeType)
  const size = asNumber(artifact.size)
  const mtimeMs = asNumber(artifact.mtimeMs)
  const sha256 = asString(artifact.sha256)

  if (fileUrl) sanitized.fileUrl = fileUrl
  if (name) sanitized.name = name
  if (mimeType) sanitized.mimeType = mimeType
  if (size !== undefined) sanitized.size = size
  if (mtimeMs !== undefined) sanitized.mtimeMs = mtimeMs
  if (sha256) sanitized.sha256 = sha256

  return sanitized
}

// Rebuilds uploaded file references without accepting embedded content or unknown payloads.
const sanitizeUploadedAttachment = (
  attachment: unknown
): PersistedUploadedAttachment | undefined => {
  if (!isRecord(attachment)) return undefined

  const id = asString(attachment.id)
  const sessionId = asString(attachment.sessionId)
  const name = asString(attachment.name)
  const path = asString(attachment.path)

  if (!id || !sessionId || !name || !path) return undefined

  const sanitized: PersistedUploadedAttachment = {
    id,
    sessionId,
    name,
    originalName: asString(attachment.originalName) ?? name,
    path,
    size: asNumber(attachment.size) ?? 0
  }
  const mimeType = asString(attachment.mimeType)

  if (mimeType) sanitized.mimeType = mimeType

  return sanitized
}

// Persisting more than the UI shows is wasteful, so bound the large text-bearing fields.
const MAX_PERSISTED_TEXT_CHARS = 16_000
const MAX_PERSISTED_TOOL_CONTENT_CHARS = 32_000
const MAX_PERSISTED_RAW_CHARS = 8_000

// Truncates oversized text with a trailing marker; a no-op when already within bounds (idempotent).
const capText = (text: string, max: number): string =>
  text.length > max ? `${text.slice(0, max)}\n…` : text

// Reads a bounded string field, returning undefined when empty.
const asCappedString = (value: unknown, max: number): string | undefined => {
  const text = asString(value)

  return text ? capText(text, max) : undefined
}

// Rebuilds a displayable content block (text/resource/link), dropping heavy binary payloads.
const sanitizeContentBlock = (block: unknown): Record<string, unknown> | undefined => {
  if (!isRecord(block)) return undefined

  switch (asString(block.type)) {
    case 'text': {
      const text = asCappedString(block.text, MAX_PERSISTED_TEXT_CHARS)

      return text !== undefined ? { type: 'text', text } : undefined
    }
    case 'resource_link': {
      const uri = asString(block.uri)

      if (!uri) return undefined

      const link: Record<string, unknown> = { type: 'resource_link', uri }
      const name = asString(block.name)
      const title = asString(block.title)

      if (name) link.name = name
      if (title) link.title = title

      return link
    }
    case 'resource': {
      if (!isRecord(block.resource)) return undefined

      const uri = asString(block.resource.uri)
      const text = asCappedString(block.resource.text, MAX_PERSISTED_TEXT_CHARS)
      const resource: Record<string, unknown> = {}

      if (uri) resource.uri = uri
      if (text !== undefined) resource.text = text

      return Object.keys(resource).length > 0 ? { type: 'resource', resource } : undefined
    }
    default:
      return undefined
  }
}

// Rebuilds one ToolCallContent entry, keeping only the text/diff shapes the detail views read.
const sanitizeToolContentEntry = (entry: unknown): Record<string, unknown> | undefined => {
  if (!isRecord(entry)) return undefined

  const type = asString(entry.type)

  if (type === 'content') {
    const content = sanitizeContentBlock(entry.content)

    return content ? { type: 'content', content } : undefined
  }
  if (type === 'diff') {
    const path = asString(entry.path)

    if (!path) return undefined

    const oldText = asString(entry.oldText)

    return {
      type: 'diff',
      path,
      oldText: oldText !== undefined ? capText(oldText, MAX_PERSISTED_TEXT_CHARS) : null,
      newText: capText(asString(entry.newText) ?? '', MAX_PERSISTED_TEXT_CHARS)
    }
  }

  // Terminal references carry no data in this app and other shapes are not rendered; drop them.
  return undefined
}

// Sanitizes tool content into a bounded array, stopping once the total budget is exhausted.
const sanitizeToolContent = (value: unknown): unknown[] | undefined => {
  if (!Array.isArray(value)) return undefined

  const entries: unknown[] = []
  let usedChars = 0

  for (const rawEntry of value) {
    const entry = sanitizeToolContentEntry(rawEntry)

    if (!entry) continue

    usedChars += JSON.stringify(entry).length

    if (usedChars > MAX_PERSISTED_TOOL_CONTENT_CHARS) break

    entries.push(entry)
  }

  return entries.length > 0 ? entries : undefined
}

// Keeps small raw input/output payloads verbatim but drops oversized ones (e.g. base64 file bytes).
const sanitizeRawPayload = (value: unknown): unknown | undefined => {
  if (value === undefined || value === null) return undefined

  try {
    const serialized = JSON.stringify(value)

    if (serialized === undefined || serialized.length > MAX_PERSISTED_RAW_CHARS) return undefined

    return JSON.parse(serialized) as unknown
  } catch {
    return undefined
  }
}

// Rebuilds tool file locations from path/line fields only.
const sanitizeToolLocations = (value: unknown): PersistedToolCallLocation[] | undefined => {
  if (!Array.isArray(value)) return undefined

  const locations = value
    .map((location): PersistedToolCallLocation | undefined => {
      if (!isRecord(location)) return undefined

      const path = asString(location.path)

      if (!path) return undefined

      const line = asNumber(location.line)

      return line !== undefined ? { path, line } : { path }
    })
    .filter((location): location is PersistedToolCallLocation => !!location)

  return locations.length > 0 ? locations : undefined
}

// Accepts only known tool-activity statuses, defaulting unknown values to completed.
const asToolActivityStatus = (value: unknown): PersistedToolActivityStatus => {
  const status = asString(value) as PersistedToolActivityStatus | undefined

  return status && TOOL_ACTIVITY_STATUSES.has(status) ? status : 'completed'
}

// Rebuilds a persisted tool activity from durable fields, bounding every large payload.
export const sanitizeToolActivity = (activity: unknown): PersistedToolActivity | undefined => {
  if (!isRecord(activity)) return undefined

  const id = asString(activity.id)

  if (!id) return undefined

  const sanitized: PersistedToolActivity = {
    id,
    kind: 'tool',
    title: asString(activity.title) ?? '',
    status: asToolActivityStatus(activity.status),
    sortIndex: asNumber(activity.sortIndex) ?? 0,
    eventIds: asStringArray(activity.eventIds),
    createdAt: asNumber(activity.createdAt) ?? 0,
    updatedAt: asNumber(activity.updatedAt) ?? 0
  }
  const providerToolName = asString(activity.providerToolName)
  const activityGroupId = asString(activity.activityGroupId)
  const toolKind = asString(activity.toolKind)
  const toolContent = sanitizeToolContent(activity.toolContent)
  const toolLocations = sanitizeToolLocations(activity.toolLocations)
  const rawInput = sanitizeRawPayload(activity.rawInput)
  const rawOutput = sanitizeRawPayload(activity.rawOutput)
  const terminalOutput = asCappedString(activity.terminalOutput, MAX_PERSISTED_TEXT_CHARS)
  const terminalExitCode = asNumber(activity.terminalExitCode)

  if (providerToolName) sanitized.providerToolName = providerToolName
  if (activityGroupId) sanitized.activityGroupId = activityGroupId
  if (toolKind) sanitized.toolKind = toolKind
  if (toolContent) sanitized.toolContent = toolContent
  if (toolLocations) sanitized.toolLocations = toolLocations
  if (rawInput !== undefined) sanitized.rawInput = rawInput
  if (rawOutput !== undefined) sanitized.rawOutput = rawOutput
  if (terminalOutput !== undefined) sanitized.terminalOutput = terminalOutput
  if (terminalExitCode !== undefined) sanitized.terminalExitCode = terminalExitCode

  return sanitized
}

// Runtime activity state cannot resume after a restart, so restore open activities as failed.
const normalizeActivityAfterRestore = (activity: PersistedToolActivity): PersistedToolActivity =>
  activity.status === 'pending' || activity.status === 'in_progress'
    ? { ...activity, status: 'failed' }
    : activity

export const sanitizeActivityGroup = (group: unknown): PersistedActivityGroup | undefined => {
  if (!isRecord(group)) return undefined

  const id = asString(group.id)
  const title = sanitizeActivityGroupTitle(group.title)
  if (!id || !title) return undefined

  const updatedAt = asNumber(group.updatedAt) ?? 0
  const completedAt = asNumber(group.completedAt)
  return {
    id,
    title,
    sortIndex: asNumber(group.sortIndex) ?? 0,
    activityIds: asStringArray(group.activityIds),
    createdAt: asNumber(group.createdAt) ?? 0,
    updatedAt,
    ...(completedAt === undefined ? {} : { completedAt })
  }
}

const normalizeActivityGroupAfterRestore = (
  group: PersistedActivityGroup
): PersistedActivityGroup =>
  group.completedAt === undefined ? { ...group, completedAt: group.updatedAt } : group

// Rebuilds one structured mention segment, dropping malformed entries so the bubble stays renderable.
const sanitizeMessagePart = (part: unknown): MessagePart | undefined => {
  if (!isRecord(part)) return undefined

  switch (asString(part.type)) {
    case 'text': {
      const text = asString(part.text)

      return text !== undefined ? { type: 'text', text } : undefined
    }
    case 'skill': {
      const id = asString(part.id)
      const name = asString(part.name)

      return id && name ? { type: 'skill', id, name } : undefined
    }
    case 'artifact': {
      const id = asString(part.id)
      const name = asString(part.name)
      const source = asString(part.source)

      if (!id || !name) return undefined

      const mimeType = asString(part.mimeType)
      if (source === 'linked-folder') {
        const rootId = asString(part.rootId)
        const relativePath = asString(part.relativePath)
        if (!rootId || !relativePath) return undefined

        return {
          type: 'artifact',
          id,
          name,
          source,
          rootId,
          relativePath,
          ...(mimeType ? { mimeType } : {})
        }
      }

      const path = asString(part.path)
      if (!path || (source !== 'upload' && source !== 'artifact')) return undefined

      const sanitized: MessagePart = { type: 'artifact', id, name, path, source }
      const versionId = asString(part.versionId)

      return {
        ...sanitized,
        ...(mimeType ? { mimeType } : {}),
        ...(versionId ? { versionId } : {})
      }
    }
    default:
      return undefined
  }
}

// Revalidates embedded message images before writing or restoring a session file. The count and
// aggregate byte budget prevent many individually valid chunks from growing one message without bound.
export const sanitizeMessageImages = (value: unknown): PersistedMessageImage[] | undefined => {
  if (!Array.isArray(value)) return undefined

  const images: PersistedMessageImage[] = []
  let totalBytes = 0

  for (const candidate of value) {
    if (images.length >= MAX_ACP_MESSAGE_IMAGES_PER_MESSAGE || !isRecord(candidate)) break

    const id = asString(candidate.id)
    const image = sanitizeAcpMessageImage(candidate)

    if (!id || !image) continue
    if (totalBytes + image.byteLength > MAX_ACP_MESSAGE_IMAGE_BYTES_PER_MESSAGE) break

    images.push({ id, ...image })
    totalBytes += image.byteLength
  }

  return images.length > 0 ? images : undefined
}

// Applies the image boundary immediately before repository serialization without changing runtime
// status fields (running sessions must remain restorable as interrupted sessions after a restart).
export const sanitizeSessionMessageImages = (
  session: PersistedChatSession
): PersistedChatSession => {
  let totalBytes = 0

  return {
    ...session,
    messages: session.messages.map((message) => {
      const images = (sanitizeMessageImages(message.images) ?? []).filter((image) => {
        if (totalBytes + image.byteLength > MAX_ACP_SESSION_IMAGE_BYTES) return false
        totalBytes += image.byteLength
        return true
      })
      return { ...message, images: images.length > 0 ? images : undefined }
    })
  }
}

// Rebuilds a message from durable UI fields and strips unknown renderer payload.
const sanitizeMessage = (message: unknown): PersistedChatMessage | undefined => {
  if (!isRecord(message)) return undefined

  const id = asString(message.id)
  const role = asMessageRole(message.role)
  const content = asString(message.content)

  if (!id || !role || content === undefined) return undefined

  const sanitized: PersistedChatMessage = {
    id,
    role,
    content,
    status: asMessageStatus(message.status),
    eventIds: asStringArray(message.eventIds),
    createdAt: asNumber(message.createdAt) ?? 0,
    updatedAt: asNumber(message.updatedAt) ?? 0
  }
  const streamId = asString(message.streamId)
  const responseToMessageId = asString(message.responseToMessageId)
  const artifactIds = asStringArray(message.artifactIds)
  const uploads = Array.isArray(message.uploads)
    ? message.uploads
        .map(sanitizeUploadedAttachment)
        .filter((item): item is PersistedUploadedAttachment => !!item)
    : []
  const parts = Array.isArray(message.parts)
    ? message.parts.map(sanitizeMessagePart).filter((item): item is MessagePart => !!item)
    : []
  const images = sanitizeMessageImages(message.images)

  if (streamId) sanitized.streamId = streamId
  if (responseToMessageId) sanitized.responseToMessageId = responseToMessageId
  if (artifactIds.length > 0) sanitized.artifactIds = artifactIds
  if (uploads.length > 0) sanitized.uploads = uploads
  if (parts.length > 0) sanitized.parts = parts
  if (images) sanitized.images = images

  return sanitized
}

// Keeps the active run pointer only when both its message id and timestamp are valid.
const sanitizeActiveRun = (activeRun: unknown): PersistedActiveRun | undefined => {
  if (!isRecord(activeRun)) return undefined

  const promptMessageId = asString(activeRun.promptMessageId)
  const startedAt = asNumber(activeRun.startedAt)

  return promptMessageId && startedAt !== undefined ? { promptMessageId, startedAt } : undefined
}

// Rebuilds a persisted chat session and normalizes any runtime-only interrupted state.
const sanitizeSession = (session: unknown): PersistedChatSession | undefined => {
  if (!isRecord(session)) return undefined

  const id = asString(session.id)

  if (!id) return undefined

  const artifacts = Array.isArray(session.artifacts)
    ? session.artifacts.map(sanitizeArtifact).filter((item): item is PersistedArtifact => !!item)
    : []
  const activities = Array.isArray(session.activities)
    ? session.activities
        .map(sanitizeToolActivity)
        .filter((item): item is PersistedToolActivity => !!item)
        .map(normalizeActivityAfterRestore)
    : []
  const activityGroups = Array.isArray(session.activityGroups)
    ? session.activityGroups
        .map(sanitizeActivityGroup)
        .filter((item): item is PersistedActivityGroup => !!item)
        .map(normalizeActivityGroupAfterRestore)
    : []
  const sanitized: PersistedChatSession = {
    id,
    // Content value is a hint; the repository overrides it with the session file's directory on load.
    projectId: asString(session.projectId) ?? '',
    title: asString(session.title) ?? id,
    cwd: asString(session.cwd) ?? '',
    status: asSessionStatus(session.status),
    permissionProfile:
      session.permissionProfile === undefined
        ? DEFAULT_PERMISSION_PROFILE
        : normalizePermissionProfile(session.permissionProfile),
    // Auto-review defaults off: a missing or non-boolean value restores as disabled, and only an
    // explicit true turns it on.
    autoReviewEnabled: session.autoReviewEnabled === true ? true : false,
    messages: Array.isArray(session.messages)
      ? session.messages.map(sanitizeMessage).filter((item): item is PersistedChatMessage => !!item)
      : [],
    createdAt: asNumber(session.createdAt) ?? 0,
    updatedAt: asNumber(session.updatedAt) ?? 0
  }
  const activeRun = sanitizeActiveRun(session.activeRun)
  const error = asString(session.error)
  const agentFrameworkId = asString(session.agentFrameworkId) as AgentFrameworkId | undefined
  const agentBackendId = asString(session.agentBackendId)
  const agentModel = asString(session.agentModel)
  const enabledComputeHosts = Array.isArray(session.enabledComputeHosts)
    ? session.enabledComputeHosts.filter(
        (item): item is string => typeof item === 'string' && item.startsWith('ssh:')
      )
    : []

  if (activeRun) sanitized.activeRun = activeRun
  if (error) sanitized.error = error
  // Only meaningful alongside an error; persisted only when explicitly false (absent = reportable).
  if (error && session.errorReportable === false) sanitized.errorReportable = false
  if (agentFrameworkId && AGENT_FRAMEWORK_IDS.has(agentFrameworkId)) {
    sanitized.agentFrameworkId = agentFrameworkId
  }
  if (agentBackendId) sanitized.agentBackendId = agentBackendId
  if (agentModel) sanitized.agentModel = agentModel
  // Restore the pin only from an explicit true so malformed or legacy files stay unpinned.
  if (session.pinned === true) sanitized.pinned = true
  // Only a non-empty string survives: an absent/empty/corrupt field resolves to None at runtime
  // rather than leaving a dangling id that the fail-closed resolver would treat as unavailable.
  const specialistId = asString(session.specialistId)
  if (specialistId) sanitized.specialistId = specialistId
  if (artifacts.length > 0) sanitized.artifacts = artifacts
  const filesRevision = asNumber(session.filesRevision)
  if (filesRevision !== undefined && Number.isInteger(filesRevision) && filesRevision >= 0) {
    sanitized.filesRevision = filesRevision
  }
  if (activities.length > 0) sanitized.activities = activities
  if (activityGroups.length > 0) sanitized.activityGroups = activityGroups
  if (enabledComputeHosts.length > 0) sanitized.enabledComputeHosts = enabledComputeHosts

  return sanitizeSessionMessageImages(normalizeSessionAfterRestore(sanitized))
}

// ---------------------------------------------------------------------------
// Per-session file storage (sessions/<projectId>/<sessionId>.json) + manifest.
// ---------------------------------------------------------------------------

// Durable envelope for a single session file; the version allows future per-file migrations.
export type PersistedSessionFile = {
  version: typeof SESSION_FILE_VERSION
  session: PersistedChatSession
}

// Wraps a session in the on-disk envelope written per file.
export const createSessionFile = (session: PersistedChatSession): PersistedSessionFile => ({
  version: SESSION_FILE_VERSION,
  session
})

// Reads one session-file payload, tolerating either the envelope or a bare session object, and applies
// the same sanitization + interrupted-run normalization used by the legacy whole-state loader.
export const normalizeSessionFile = (value: unknown): PersistedChatSession | undefined => {
  if (!isRecord(value)) return undefined

  const rawSession = isRecord(value.session) ? value.session : value

  return sanitizeSession(rawSession)
}

// Tiny app-level pointer restoring the last-open project + session after a restart.
export type PersistedSessionManifest = {
  version: typeof SESSION_MANIFEST_VERSION
  lastProjectId?: string
  lastSessionId?: string
}

// Canonical empty manifest for missing/unusable manifest files.
export const createEmptySessionManifest = (): PersistedSessionManifest => ({
  version: SESSION_MANIFEST_VERSION
})

// Rebuilds a manifest from allowed string fields, dropping anything else.
export const normalizeSessionManifest = (value: unknown): PersistedSessionManifest => {
  if (!isRecord(value)) return createEmptySessionManifest()

  const manifest: PersistedSessionManifest = { version: SESSION_MANIFEST_VERSION }
  const lastProjectId = asString(value.lastProjectId)
  const lastSessionId = asString(value.lastSessionId)

  if (lastProjectId) manifest.lastProjectId = lastProjectId
  if (lastSessionId) manifest.lastSessionId = lastSessionId

  return manifest
}

// IPC payloads for the per-session persistence surface.
export type LoadAllSessionsResult = {
  sessions: PersistedChatSession[]
  manifest: PersistedSessionManifest
}

export type DeleteSessionRequest = {
  projectId: string
  sessionId: string
}

export type SaveSessionManifestRequest = {
  lastProjectId?: string
  lastSessionId?: string
}
